# Generated by Django 3.2.7 on 2021-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Task Name')),
                ('status', models.CharField(choices=[('u', 'Not started'), ('o', 'ongoing'), ('f', 'Finished')], max_length=1, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Our Task',
                'verbose_name_plural': 'Our Task',
            },
        ),
    ]
