# Generated by Django 3.2.7 on 2021-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Course Name')),
                ('weekday', models.IntegerField(verbose_name='Weekday')),
                ('start_time', models.TimeField(auto_now=True, verbose_name='Start Time')),
                ('finish_time', models.TimeField(auto_now=True, verbose_name='Finish Time')),
            ],
        ),
    ]
