# Generated by Django 3.2.7 on 2021-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_student_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
