# Generated by Django 3.2.7 on 2021-11-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_signin_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.course')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.student')),
            ],
        ),
    ]
