# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 596)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/android.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/background/background.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 80, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.label.setObjectName("label")
        self.faceView = QtWidgets.QLabel(self.centralwidget)
        self.faceView.setGeometry(QtCore.QRect(80, 160, 291, 221))
        self.faceView.setStyleSheet("background-image: url(:/imageView/face.jpg);")
        self.faceView.setText("")
        self.faceView.setObjectName("faceView")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(80, 430, 561, 81))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.registrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.registrationButton.setGeometry(QtCore.QRect(450, 190, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(11)
        self.registrationButton.setFont(font)
        self.registrationButton.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.registrationButton.setIcon(icon)
        self.registrationButton.setObjectName("registrationButton")
        self.identificationButton = QtWidgets.QPushButton(self.centralwidget)
        self.identificationButton.setGeometry(QtCore.QRect(450, 290, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(11)
        self.identificationButton.setFont(font)
        self.identificationButton.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.identificationButton.setIcon(icon)
        self.identificationButton.setObjectName("identificationButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.registrationButton.clicked.connect(MainWindow.execRegistration)
        self.identificationButton.clicked.connect(MainWindow.execIdentification)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face-Recognition-Sign-In-System"))
        self.label.setText(_translate("MainWindow", "Hello, Student !!"))
        self.registrationButton.setText(_translate("MainWindow", "Registration"))
        self.identificationButton.setText(_translate("MainWindow", "Identification"))