# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registrationDialog(object):
    def setupUi(self, registrationDialog):
        registrationDialog.setObjectName("registrationDialog")
        registrationDialog.resize(541, 354)
        self.label = QtWidgets.QLabel(registrationDialog)
        self.label.setGeometry(QtCore.QRect(180, 10, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(registrationDialog)
        self.label_3.setGeometry(QtCore.QRect(100, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.nameEdit = QtWidgets.QLineEdit(registrationDialog)
        self.nameEdit.setGeometry(QtCore.QRect(270, 140, 113, 21))
        self.nameEdit.setObjectName("nameEdit")
        self.label_4 = QtWidgets.QLabel(registrationDialog)
        self.label_4.setGeometry(QtCore.QRect(130, 80, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.idEdit = QtWidgets.QLineEdit(registrationDialog)
        self.idEdit.setGeometry(QtCore.QRect(270, 80, 113, 21))
        self.idEdit.setObjectName("idEdit")
        self.photoButton = QtWidgets.QPushButton(registrationDialog)
        self.photoButton.setGeometry(QtCore.QRect(120, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.photoButton.setFont(font)
        self.photoButton.setObjectName("photoButton")
        self.addButton = QtWidgets.QPushButton(registrationDialog)
        self.addButton.setGeometry(QtCore.QRect(220, 270, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setAutoFillBackground(False)
        self.addButton.setObjectName("addButton")
        self.imgEdit = QtWidgets.QLineEdit(registrationDialog)
        self.imgEdit.setEnabled(False)
        self.imgEdit.setGeometry(QtCore.QRect(270, 200, 113, 21))
        self.imgEdit.setObjectName("imgEdit")
        self.face_label = QtWidgets.QLabel(registrationDialog)
        self.face_label.setGeometry(QtCore.QRect(410, 70, 80, 80))
        self.face_label.setText("")
        self.face_label.setScaledContents(True)
        self.face_label.setObjectName("face_label")

        self.retranslateUi(registrationDialog)
        self.photoButton.clicked.connect(registrationDialog.takePhoto)
        self.addButton.clicked.connect(registrationDialog.addUser)
        QtCore.QMetaObject.connectSlotsByName(registrationDialog)

    def retranslateUi(self, registrationDialog):
        _translate = QtCore.QCoreApplication.translate
        registrationDialog.setWindowTitle(_translate("registrationDialog", "Registration"))
        self.label.setText(_translate("registrationDialog", "Registration"))
        self.label_3.setText(_translate("registrationDialog", "Student Name"))
        self.label_4.setText(_translate("registrationDialog", "Student ID"))
        self.photoButton.setText(_translate("registrationDialog", "Take Photo"))
        self.addButton.setText(_translate("registrationDialog", "Add"))
